<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>Packer.WinUI3</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<Nullable>enable</Nullable>

		<WindowsPackageType>None</WindowsPackageType>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

		<EnablePriResourceMerge>false</EnablePriResourceMerge>
		<ResourceLanguages>en-US</ResourceLanguages>
		<DefaultLanguage>en-US</DefaultLanguage>

		<GenerateResourceIndexingFlags>0</GenerateResourceIndexingFlags>

	</PropertyGroup>



	<ItemGroup>
	  <None Remove="Styles\KadmiumTheme.xaml" />
	  <None Remove="Views\SettingsView.xaml" />
	</ItemGroup>


	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>


	<ItemGroup>
	  <None Include="..\..\..\..\Desktop\Legal\LICENSE.txt">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Packer.Core\Packer.Core.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <Content Update="Assets\Fonts\Inter-italic.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Fonts\Inter-regular.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Fonts\Michroma-Regular.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Logos\BootstrapperIcon.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Logos\BootstrapperLogo.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>


	<ItemGroup>
	  <None Update="Assets\Fonts\Inter-italic.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Assets\Fonts\Inter-regular.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Assets\Fonts\Michroma-Regular.ttf">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="LICENSE.txt">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <Page Update="Styles\KadmiumTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Views\PackerMainView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Views\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>

	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
		<ApplicationIcon>Assets\Logos\BootstrapperIcon.ico</ApplicationIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

</Project>
